#!/bin/bash
set -a

# user input
SYSTEM=
NEKRS_HOME=
VENV_PATH="${PWD}/../_env"
NODES=
TIME="01:00"
PROJ_ID="datascience"
DEPLOYMENT="offline"
CLIENT="posix"
ML_TASK=
DB_NODES=1
SIM_NODES=1
TRAIN_NODES=1
MODEL=
ENSEMBLE=
# case name is found automatically
CASE_NAME=

function print_help() {
  echo -e "Usage: $0 <SYSTEM> <NEKRS_HOME> [--venv_path | -v <VENV_PATH>]"\
    "[--nodes | -n <NODES>] [--time | -t <TIME>]\n\t"                     \
    "[--proj_id | -p <PROJ_ID>] [--model | -m <MODEL>]"                   \
    "[--deployment | -d <DEPLOYMENT>] [--ml_task | -ml <ML_TASK>]"        \
    "[--client | -c <CLIENT>]\n\t"                                        \
    "[--db_nodes | -dn <DB_NODES>] [--sim_nodes | -sn <SIM_NODES>]"       \
    "[--train_nodes | -tn <TRAIN_NODES>]\n\t"                             \
    "[--ensemble | -e <ENSEMBLE>] [--help | -h]"
}

function parse_args() {
  if [ "$#" -lt 2 ]; then
    print_help
    exit 1
  fi

  SYSTEM="${1,,}"
  shift
  NEKRS_HOME=$1
  shift

  while [ $# -gt 0 ]; do
    key="$1"
    case $key in
      --venv_path| -v)
        VENV_PATH=$2
        shift; shift
        ;;
      --nodes| -n)
        NODES=$2
        shift; shift
        ;;
      --time| -t)
        TIME=$2
        shift; shift
        ;;
      --proj_id| -p)
        PROJ_ID=$2
        shift; shift
        ;;
      --model| -m)
        MODEL=${2,,}
        shift; shift
        ;;
      --deployment| -d)
        DEPLOYMENT=${2,,}
        shift; shift
        ;;
      --ml_task| -ml)
        ML_TASK=${2,,}
        shift; shift
        ;;
      --client| -c)
        CLIENT=${2,,}
        shift; shift
        ;;
      --db_nodes| -dn)
        DB_NODES=$2
        shift; shift
        ;;
      --sim_nodes| -sn)
        SIM_NODES=$2
        shift; shift
        ;;
      --train_nodes| -tn)
        TRAIN_NODES=$2
        shift; shift
        ;;
      --ensemble| -e)
        ENSEMBLE=${2,,}
        shift; shift
        ;;
      --help| -h)
        print_help
        exit 0
        ;;
      *)
        print_help
        exit 1
    esac
  done

  # If nodes was not set, check if available from interactive session PBVS env
  if [ -z "${NODES}" ]; then
    if [ ! -z "${PBS_NODEFILE}" ]; then
      NODES=$(cat ${PBS_NODEFILE} | wc -l)
    fi
  fi

  # Append model and client to VENV_PATH as what is installed in the environment
  # depends on the model and the client.
  if [ -n "${MODEL}" ]; then
    VENV_PATH=${VENV_PATH}_${MODEL}
  fi
  if [ -n "${CLIENT}" ]; then
    VENV_PATH=${VENV_PATH}_${CLIENT}
  fi
  if [ -n "${ENSEMBLE}" ]; then
    VENV_PATH=${VENV_PATH}_${ENSEMBLE}
  fi
}

function check_args() {
  if [ -z "${NODES}" ]; then
    echo "Number of nodes was not specified, use --nodes or -n to specify the nodes or run from an interactive session"
    exit 1
  fi
  if [ "${SYSTEM}" != "aurora" ] && [ "${SYSTEM}" != "polaris" ] && [ "${SYSTEM}" != "crux" ]; then
    echo "Invalid system name! Supported systems are aurora, polaris and crux."
    exit 1
  fi
  if [ ! -d "${NEKRS_HOME}" ]; then
    echo "NEKRS_HOME does not exist! Check path."
    exit 1
  fi
  if [ -n "${MODEL}" ] && [ "${MODEL}" != "dist-gnn" ] && [ "${MODEL}" != "sr-gnn" ]; then
    echo "Invalid model type! Supported options are dist-gnn and sr-gnn."
    exit 1
  fi
  if [ "${DEPLOYMENT}" != "clustered" ] && [ "${DEPLOYMENT}" != "colocated" ] && [ "${DEPLOYMENT}" != "offline" ]; then
    echo "Invalid deployment type! Supported options are offline, clustered and colocated."
    exit 1
  fi
  if [ "${MODEL}" = "sr-gnn" ] && [ "${DEPLOYMENT}" != "offline" ]; then
    echo "Currently, sr-gnn model is only supported with offline deployment."
    exit 1
  fi
  if [ -n "${ML_TASK}" ] && [ "${ML_TASK}" != "train" ] && [ "${ML_TASK}" != "inference" ]; then
    echo "Invalid deployment type! Supported options are undefined, train and inference."
    exit 1
  fi
  if [ "${CLIENT}" != "smartredis" ] && [ "${CLIENT}" != "adios" ] && [ "${CLIENT}" != "posix" ]; then
    echo "Invalid client type! Supported options are posix, smartredis and adios."
    exit 1
  fi
  if [ "${DEPLOYMENT}" == "colocated" ]; then
    if [ "$SIM_NODES" -ne "$NODES" ] && [ "$TRAIN_NODES" -ne "$NODES" ]; then
      echo "Invalid number of simulation and/or training nodes."
      echo "The number of simulation and training nodes must equal the number of nodes of the job."
      exit 1
    fi
    if [ "$DB_NODES" -ne "1" ]; then
      echo "Invalid number of database nodes."
      echo "With the colocated deployment, the database nodes is set to 1 since it is not sharded."
      exit 1
    fi
  fi
  if [ "${DEPLOYMENT}" == "clustered" ]; then
    if [ "${CLIENT}" == "smartredis" ]; then
      if [ "$DB_NODES" -eq "2" ]; then
        echo "Invalid number of database nodes."
        echo "SmartSim does not allow clustered databases of 2 nodes, DB_NODES can be 1 or >=3."
        exit 1
      fi
      if [ $((DB_NODES + SIM_NODES + TRAIN_NODES)) -ne "$NODES" ]; then
        echo "Invalid number of database, simulation and training nodes."
        echo "The sum of nodes assigned to each component must equal the total number of nodes of the job."
        exit 1
      fi
    fi
    if [ "${CLIENT}" == "adios" ]; then
      if [ $((SIM_NODES + TRAIN_NODES)) -ne "$NODES" ]; then
        echo "Invalid number of simulation and training nodes."
        echo "The sum of nodes assigned to each component must equal the total number of nodes of the job."
        exit 1
      fi
    fi
  fi
  if [ -n "${ENSEMBLE}" ] && [ "${ENSEMBLE}" != "el" ]; then
    echo "Invalid ensemble type! Supported options are el (EnsembleLauncher)."
    exit 1
  fi
}

function check_connection() {
  if ! curl -Is --max-time 5 https://example.com >/dev/null; then
    echo "Connection test failed — check proxy or network settings." >&2
    exit 1
  fi
}

function setup_case() {
  if [ "$ML_TASK" == "train" ]; then
    # turbChannel_wallModel_ML example
    CASE_NAME=$(ls *_train.par)
    CASE_NAME=${CASE_NAME:0:${#CASE_NAME}-10}
  elif [ "$ML_TASK" == "inference" ]; then
    # turbChannel_wallModel_ML example
    CASE_NAME=$(ls *_inference.par)
    CASE_NAME=${CASE_NAME:0:${#CASE_NAME}-14}
  elif [ "$DEPLOYMENT" == "offline" ]; then
    # offline example
    CASE_NAME=$(ls *.par)
    CASE_NAME=${CASE_NAME:0:${#CASE_NAME}-4}
  elif [ "${DEPLOYMENT}" == "colocated" ] || [ "${DEPLOYMENT}" == "clustered" ]; then
    # online example
    CASE_NAME=$(ls *.par.safe)
    CASE_NAME=${CASE_NAME:0:${#CASE_NAME}-9}
  else
    echo "Error: Unable to find case name!"
    exit 1
  fi

  if [ -n "$ML_TASK" ]; then
    cp ${CASE_NAME}_${ML_TASK}.box ${CASE_NAME}.box
    cp ${CASE_NAME}_${ML_TASK}.udf ${CASE_NAME}.udf
    cp ${CASE_NAME}_${ML_TASK}.usr ${CASE_NAME}.usr
    cp ${CASE_NAME}_${ML_TASK}.par ${CASE_NAME}.par
    cp ${CASE_NAME}_${ML_TASK}.re2 ${CASE_NAME}.re2
    cp ${CASE_NAME}_${ML_TASK}.oudf ${CASE_NAME}.oudf
  elif [ "${DEPLOYMENT}" == "colocated" ] || [ "${DEPLOYMENT}" == "clustered" ]; then
    cp ${CASE_NAME}.par.safe ${CASE_NAME}.par
  fi
}

function print_args() {
  echo "SYSTEM     : ${SYSTEM}"
  echo "NEKRS_HOME : ${NEKRS_HOME}"
  echo "VENV_PATH  : ${VENV_PATH}"
  echo "NODES      : ${NODES}"
  echo "TIME       : ${TIME}"
  echo "PROJ_ID    : ${PROJ_ID}"
  echo "MODEL      : ${MODEL}"
  echo "DEPLOYMENT : ${DEPLOYMENT}"
  echo "CLIENT     : ${CLIENT}"
  echo "ML_TASK    : ${ML_TASK}"
  echo "DB_NODES   : ${DB_NODES}"
  echo "SIM_NODES  : ${SIM_NODES}"
  echo "TRAIN_NODES: ${TRAIN_NODES}"
  echo "MODEL      : ${MODEL}"
  echo "ENSEMBLE   : ${ENSEMBLE}"
  echo "CASE_NAME  : ${CASE_NAME}"
}

# this maybe not necessary as the nrsrun_${SYSTEM} scripts generate
# them.
function load_modules() {
  if [ "${SYSTEM}" == "aurora" ]; then
    module load frameworks
    module load git-lfs
  elif [ "${SYSTEM}" == "polaris" ]; then
    module use /soft/modulefiles/
    module load conda
    conda activate
    module load spack-pe-base cmake
  elif [ "${SYSTEM}" == "crux" ]; then
    module use /soft/modulefiles/
    module load PrgEnv-gnu/8.5.0
    module load gcc-native/12.3
    module load spack-pe-base/0.8.0
    module load cmake
    module load python/3.10.13
  fi
}

function build_smartsim() {
  if [ "${SYSTEM}" == "polaris" ]; then
    export CC=cc
    export CXX=CC
    export CUDNN_BASE=/soft/libraries/cudnn/cudnn-12-linux-x64-v9.1.0.70
    export CUDNN_LIBRARY=$CUDNN_BASE/lib/
    export CUDNN_INCLUDE_DIR=$CUDNN_BASE/include/
    export LD_LIBRARY_PATH=$CUDNN_LIBRARY:$LD_LIBRARY_PATH
  fi

  pip install git+https://github.com/rickybalin/SmartRedis.git@develop
  pip install git+https://github.com/rickybalin/SmartSim.git@rollback_aurora

  if [ "${SYSTEM}" == "aurora" ]; then
    DEVICE="cpu"
  elif [ "${SYSTEM}" == "polaris" ]; then
    DEVICE="gpu"
  fi

  export TORCH_PATH=$( python -c 'import torch; print(torch.__path__[0])' )
  export LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH
  export TORCH_CMAKE_PATH=$( python -c 'import torch;print(torch.utils.cmake_prefix_path)' )
  smart build -v --device $DEVICE --torch_dir $TORCH_CMAKE_PATH --no_tf
  smart validate
}

function build_ensemblelauncher() {
  python3 -m pip install "git+https://github.com/argonne-lcf/ensemble_launcher.git"
}

function setup_venv() {
  reuse=0
  if [ -d ${VENV_PATH} ]; then
    echo -e "\033[35mPython venv \"${VENV_PATH}\" already exists, reusing it ... \033[m"
    return 0
  else
    echo -e "\033[35mPython venv \"${VENV_PATH}\" doesn't exist, building one now ...\033[m"
    python -m venv --clear ${VENV_PATH} --system-site-packages
  fi

  source ${VENV_PATH}/bin/activate

  if [ "${SYSTEM}" == "crux" ]; then
    pip install numpy
    pip install torch --index-url https://download.pytorch.org/whl/cpu
    MPICC="cc -shared" pip install --force-reinstall --no-cache-dir --no-binary=mpi4py mpi4py
  fi

  export TORCH_PATH=$( python -c 'import torch; print(torch.__path__[0])' )
  export LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH
  if [ "${SYSTEM}" == "aurora" ] && [ -n "${MODEL}" ]; then
    pip install torch_geometric==2.5.3
  fi  

  if [ "${MODEL}" == "sr-gnn" ] && [ "${SYSTEM}" == "aurora" ]; then
    cwd=${PWD}
    git clone https://github.com/rusty1s/pytorch_cluster.git ${VENV_PATH}/pytorch_cluster
    cd ${VENV_PATH}/pytorch_cluster
    # Need to force the install to not link with OpenMP, change lines 53-54 to if False:
    sed -i 's/fopenmp/lgomp/' setup.py
    CXX=$(which dpcpp) python setup.py install
    cd ${cwd}
  fi
  
  pip install pymech

  if [ "${CLIENT}" == "smartredis" ]; then
    build_smartsim
  fi

  if [ "${ENSEMBLE}" == "el" ]; then
    build_ensemblelauncher
  fi

  deactivate
}

function generate_script() {
  NEKRS_HOME=${NEKRS_HOME} VENV_PATH=${VENV_PATH}/bin/activate PROJ_ID=${PROJ_ID} \
  DB_NODES=$DB_NODES SIM_NODES=$SIM_NODES TRAIN_NODES=$TRAIN_NODES \
  DEPLOYMENT=$DEPLOYMENT ML_TASK=${ML_TASK} \
  ${PWD}/nrsrun_${SYSTEM} ${CASE_NAME} ${NODES} ${TIME}
}

parse_args "$@"
print_args
check_args
check_connection
setup_case
load_modules
setup_venv
generate_script
