#!/bin/bash

: ${SYSTEM:="aurora:compute"}
: ${PREFIX:="${PWD}/test_data"}
#: ${COMMIT="main"}
: ${COMMIT="$(git -C "$(dirname "$0")/.." rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"}
: ${QUEUE:="prod"}
: ${PROJECT:="datascience"}
: ${FS:="home"}
: ${REUSE:=1}
: ${TAG:="all"}
: ${LIST_TAGS:=0}
: ${POLICY:=async}
: ${CONFIG_FILE:="sites.py"}

# Parse command line args
# =======================

print_help() {
  echo "Usage: $(basename "$0") [options]"
  echo ""
  echo "Options:"
  echo "  --build,       -b                    Build test dependencies from scratch (do not reuse)"
  echo "  --clean,       -c                    Clean the temporary files generated by Python etc."
  echo "  --commit,      -cm  <COMMIT>         Set the git commit to checkout (Default: $COMMIT)"
  echo "  --exec-policy, -e   <POLICY>         Set test execution policy (Default: $POLICY)"
  echo "  --filesystems, -f   <FS>             Set the filesystems (Default: $FS)"
  echo "  --help,        -h                    Show this help message and exit"
  echo "  --list-tags,   -l                    List the available test tags"
  echo "  --prefix,      -p   <PREFIX>         Set the installation prefix (Default: $PREFIX)"
  echo "  --project,     -prj <PROJECT>        Set the project name (Default: $PROJECT)"
  echo "  --queue,       -q   <QUEUE>          Set the job queue (Default: $QUEUE)"
  echo "  --system,      -s   <SYSTEM>         Set the system name (Default: $SYSTEM)"
  echo "  --tag,         -t   <TAG>            Run the tests with tag TAG (Default: $TAG)"
  echo "  --config-file, -cfg <CONFIG_FILE>    Set the configuration file (Default: $CONFIG_FILE)"
  echo ""
  echo "Examples:"
  echo "  To run all the tests:"
  echo "    ./$(basename "$0") -t all -b"
  echo "  To run all the offline training tests:"
  echo "    ./$(basename "$0") -t offline -b"
  echo "  To run all the online training tests:"
  echo "    ./$(basename "$0") -t online -b"
  echo "  To run all the tests based on TGV case:"
  echo "    ./$(basename "$0") -t tgv -b"
  echo "  To run just the tgv_offline test:"
  echo "    ./$(basename "$0") -t tgv_offline$ -b"
  echo "  To run all ensemble tests:"
  echo "    ./$(basename "$0") -t ensemble -b"
  echo "  To run only the periodicHill ensemble test:"
  echo "    ./$(basename "$0") -t periodichill_ensemble$ -b"
  echo "  Please note that \"-b\" parameter is required only for the first run of each tag."
  echo "  You can pass --list-tags or -l to list all the test tags:"
  echo "    ./$(basename "$0") -l"
}

clean() {
  rm -rf __pycache__
}

while [ $# -gt 0 ]; do
  flag="$1"
  case $flag in
    --build| -b)
      REUSE=0
      shift
      ;;
    --clean| -c)
      clean
      ;;
    --commit| -cm)
      COMMIT=$2
      shift; shift;
      ;;
    --exec-policy| -e)
      POLICY=$2
      shift; shift
      ;;
    --filesystems| -f)
      FS="$2"
      shift; shift
      ;;
    --help| -h)
      print_help
      exit 0
      ;;
    --list-tags| -l)
      LIST_TAGS=1
      shift
      ;;
    --prefix| -p)
      PREFIX="$2"
      shift; shift
      ;;
    --project| -prj)
      PROJECT="$2"
      shift; shift
      ;;
    --queue| -q)
      QUEUE="$2"
      shift; shift
      ;;
    --system| -s)
      SYSTEM="$2"
      shift; shift
      ;;
    --tag| -t)
      TAG="$2"
      shift; shift
      ;;
    --config-file| -cfg)
      CONFIG_FILE="$2"
      shift; shift
      ;;
    *)
      print_help
      exit 1
  esac
done

# ReFrame command guide
# =====================
# --config-file: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-C
# --system: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-system
# --exec-policy: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-exec-policy
# --keep-stage-files: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-keep-stage-files
# --restore-session: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-restore-session
# --timestamp: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-timestamp
# --prefix: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-prefix
# --report-file: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-report-file
# --checkpath: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-c
# --tag: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-t
# --run: https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-r
CMD="uv --no-managed-python run reframe --save-log-files --config-file ${CONFIG_FILE}"
CMD="${CMD} --keep-stage-files --timestamp --checkpath tests.py"
CMD="${CMD} --exec-policy=${POLICY} --system ${SYSTEM} --prefix=${PREFIX}"
CMD="${CMD} -S queue=${QUEUE} -S project=${PROJECT} -S filesystems=${FS}"
CMD="${CMD} -S commit=${COMMIT}"

if [ "${LIST_TAGS}" -eq 1 ]; then
  CMD="${CMD} --list-tags"
else
  if [ "${REUSE}" -eq 1 ]; then
    CMD="${CMD} --restore-session"
  fi
  CMD="${CMD} --report-file ${PREFIX}/reports/report_{sessionid}.json --tag ${TAG} --run"
fi
module load frameworks
${CMD}
