#!/bin/bash
set -e

#--------------------------------------
: ${QUEUE:="lustre_scaling"}
: ${NEKRS_GPU_MPI:=0}
: ${NEKRS_BACKEND:="dpcpp"}
: ${RANKS_FOR_BUILD:=12}
: ${SIM_RANKS_PER_NODE:=6}
: ${TRAIN_RANKS_PER_NODE:=6}
: ${DEPLOYMENT:="colocated"}
: ${DB_NODES:=1}
: ${SIM_NODES:=1}
: ${TRAIN_NODES:=1}
: ${SIM_CPU_BIND_LIST:="1:8:16:24:32:40"}
: ${TRAIN_CPU_BIND_LIST:="53:60:68:76:84:92"}
: ${INFERENCE_CPU_BIND_LIST:="1:8:16:24:32:40:53:60:68:76:84:92"}
: ${OCCA_DPCPP_COMPILER_FLAGS:="-O3 -fsycl -fsycl-targets=intel_gpu_pvc -ftarget-register-alloc-mode=pvc:auto -fma"}
: ${ONEAPI_SDK:=""}
: ${FRAMEWORKS_MODULE:="frameworks"}
: ${VENV_PATH:=""}
#--------------------------------------

cp ${1}.par.safe ${1}.par

#--------------------------------------
# Update the .box file to increase the mesh size linearly with the number of nodes
SIM_PROCS=$(( SIM_NODES * SIM_RANKS_PER_NODE ))
NX=$(( 13 ))
NZ=$(( 2*SIM_PROCS ))
if [[ "$SIM_NODES" -gt 1 ]]; then
    LZ=$SIM_NODES
else
    LZ=1
fi
cp ${1}_safe.box ${1}.box
sed -i "s/NX/${NX}/g" ${1}.box
sed -i "s/NZ/${NZ}/g" ${1}.box
sed -i "s/LZ/${LZ}/g" ${1}.box

#--------------------------------------
# Run genbox from Nek5000 to generate the .re2 mesh file
if [ ! -d $NEKRS_HOME/Nek5000 ]; then
  CWD=$PWD
  cd $NEKRS_HOME
  git clone https://github.com/rickybalin/Nek5000.git
  cd Nek5000/tools
  FC=`which gfortran` ./maketools genbox
  cd $CWD
fi
$NEKRS_HOME/Nek5000/bin/genbox ${1}.box ${1}

#--------------------------------------
# Setup the case
source $NEKRS_HOME/bin/nrsqsub_utils
setup $# 1
chk_case $TOTAL_RANKS

#--------------------------------------
# Generate the workflow config script
CFILE=config.yaml
echo "# Database config" > $CFILE
echo "database:" >> $CFILE
echo "    launch: True" >> $CFILE
echo "    backend: \"redis\"" >> $CFILE
echo "    deployment: \"${DEPLOYMENT}\"" >> $CFILE
echo "    port: 6782" >> $CFILE
if [ ${DEPLOYMENT} == "colocated"  ]; then
  echo "    network_interface: \"uds\"" >> $CFILE
else
  echo "    network_interface: \"hsn0\"" >> $CFILE
fi
echo "    exp_name: \"nekRS-ML\"" >> $CFILE
echo "    launcher: \"pals\"" >> $CFILE
echo "" >> $CFILE
echo "# Run config" >> $CFILE
echo "run_args:" >> $CFILE
echo "    nodes: ${qnodes}" >> $CFILE
if [ ${DEPLOYMENT} == "colocated"  ]; then
  SIM_NODES=$nodes
  TRAIN_NODES=$nodes
  SIM_PROCS=$(( SIM_NODES * SIM_RANKS_PER_NODE ))
  TRAIN_PROCS=$(( TRAIN_NODES * TRAIN_RANKS_PER_NODE ))
  echo "    db_nodes: ${DB_NODES}" >> $CFILE
  echo "    sim_nodes: ${SIM_NODES}" >> $CFILE
  echo "    ml_nodes: ${SIM_NODES}" >> $CFILE
  echo "    simprocs: ${SIM_PROCS}" >> $CFILE
  echo "    simprocs_pn: ${SIM_RANKS_PER_NODE}" >> $CFILE
  echo "    mlprocs: ${TRAIN_PROCS}" >> $CFILE
  echo "    mlprocs_pn: ${TRAIN_RANKS_PER_NODE}" >> $CFILE
  echo "    dbprocs_pn: 4" >> $CFILE
  echo "    sim_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
  echo "    ml_cpu_bind: \"list:${TRAIN_CPU_BIND_LIST}\"" >> $CFILE
  echo "    db_cpu_bind: [100,101,102,103]" >> $CFILE
elif [ ${DEPLOYMENT} == "clustered"  ]; then
  SIM_PROCS=$(( SIM_NODES * SIM_RANKS_PER_NODE ))
  TRAIN_PROCS=$(( TRAIN_NODES * TRAIN_RANKS_PER_NODE ))
  echo "    db_nodes: ${DB_NODES}" >> $CFILE
  echo "    sim_nodes: ${SIM_NODES}" >> $CFILE
  echo "    ml_nodes: ${TRAIN_NODES}" >> $CFILE
  echo "    simprocs: ${SIM_PROCS}" >> $CFILE
  echo "    simprocs_pn: ${SIM_RANKS_PER_NODE}" >> $CFILE
  echo "    mlprocs: ${TRAIN_PROCS}" >> $CFILE
  echo "    mlprocs_pn: ${TRAIN_RANKS_PER_NODE}" >> $CFILE
  echo "    dbprocs_pn: 8" >> $CFILE
  echo "    sim_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
  echo "    ml_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
  echo "    db_cpu_bind: [1,2,3,4,5,6,7,8]" >> $CFILE
fi
echo "" >> $CFILE
echo "# Simulation config" >> $CFILE
echo "sim:" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/bin/nekrs\"" >> $CFILE
echo "    arguments: \"--setup ${case}.par --backend ${NEKRS_BACKEND} \"" >> $CFILE
echo "    copy_files: [\"./${case}.usr\",\"./${case}.par\",\"./${case}.udf\",\"./${case}.re2\"]" >> $CFILE
echo "    link_files: [\".cache\"]" >> $CFILE
echo "" >> $CFILE
echo "# Trainer config" >> $CFILE
echo "train:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/3rd_party/gnn/dist-gnn/main.py\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
if [ ${DEPLOYMENT} == "colocated"  ]; then
  echo "    arguments: \"device_skip=${SIM_RANKS_PER_NODE} halo_swap_mode=all_to_all_opt online=True client.db_nodes=${DB_NODES} consistency=True time_dependency=time_dependent verbose=True transform_x=true transform_z=true\"" >> $CFILE
elif [ ${DEPLOYMENT} == "clustered"  ]; then
  echo "    arguments: \"halo_swap_mode=all_to_all_opt online=True client.db_nodes=${DB_NODES} consistency=True time_dependency=time_dependent verbose=True transform_x=true transform_z=true\"" >> $CFILE
fi
echo "    copy_files: []" >> $CFILE
echo "    link_files: []" >> $CFILE
echo "" >> $CFILE
echo "# Inference config" >> $CFILE
echo "inference:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/3rd_party/gnn/dist-gnn/inference.py\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    arguments: \"model_task=inference rollout_steps=100 halo_swap_mode=all_to_all_opt online=True client.db_nodes=${DB_NODES} consistency=True time_dependency=time_dependent verbose=True transform_x=true transform_z=true\"" >> $CFILE
echo "    copy_files: []" >> $CFILE
echo "    link_files: []" >> $CFILE

#--------------------------------------
# Update the .par file with the ML options
PFILE=${case}.par
echo "" >> $PFILE
echo "[ML]" >> $PFILE
echo "gnnPolynomialOrder = 7" >> $PFILE
echo "ssimDeployment = ${DEPLOYMENT}" >> $PFILE
echo "ssimDbNodes = ${DB_NODES}" >> $PFILE

#--------------------------------------
# Generate the run script
RFILE=run.sh
echo "#!/bin/bash" > $RFILE

echo "export TZ='/usr/share/zoneinfo/US/Central'" >> $RFILE

echo -e "\necho Jobid: \$PBS_JOBID" >>$RFILE
echo "echo Running on host \`hostname\`" >>$RFILE
echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$RFILE

echo "module load ${FRAMEWORKS_MODULE}" >> $RFILE
echo "source ${VENV_PATH}" >> $RFILE
echo "module list" >> $RFILE

echo "export ZE_FLAT_DEVICE_HIERARCHY=FLAT" >> $RFILE
echo -e "\nexport NEKRS_HOME=$NEKRS_HOME" >>$RFILE
#echo "export NEKRS_GPU_MPI=$NEKRS_GPU_MPI" >>$RFILE
#echo "export MPICH_GPU_SUPPORT_ENABLED=$NEKRS_GPU_MPI" >> $RFILE

echo "export OCCA_DPCPP_COMPILER_FLAGS=\"$OCCA_DPCPP_COMPILER_FLAGS\"" >> $RFILE
echo "export FI_CXI_RX_MATCH_MODE=hybrid" >> $RFILE # required by parRSB

# Temporary workaround while waiting on bugfix in runtime
echo "export UR_L0_USE_COPY_ENGINE=0" >> $RFILE

echo -e "\nexport CCL_PROCESS_LAUNCHER=pmix" >> $RFILE
echo "export CCL_ATL_TRANSPORT=mpi" >> $RFILE
echo "export CCL_ALLREDUCE_SCALEOUT=direct:0-1048576,rabenseifner:1048577-max" >> $RFILE
echo "export CCL_KVS_CONNECTION_TIMEOUT=300" >> $RFILE
echo "export CCL_ALLTOALLV_MONOLITHIC_KERNEL=0" >> $RFILE

echo -e "\nexport SR_LOG_FILE=stdout" >> $RFILE
echo "export SR_LOG_LEVEL=QUIET" >> $RFILE
echo "export TORCH_PATH=\$( python -c 'import torch; print(torch.__path__[0])' )" >> $RFILE
echo "export LD_LIBRARY_PATH=\$TORCH_PATH/lib:\$LD_LIBRARY_PATH" >> $RFILE
echo "export SR_SOCKET_TIMEOUT=10000" >> $RFILE

echo -e "\n# precompilation" >>$RFILE
CMD_build="mpiexec -n ${RANKS_FOR_BUILD} -ppn ${RANKS_FOR_BUILD} --cpu-bind list:1:8:16:24:32:40:53:60:68:76:84:92 -- $bin --setup ${case} --backend ${NEKRS_BACKEND}  $extra_args --build-only ${RANKS_FOR_BUILD}"
add_build_CMD "$RFILE" "$CMD_build" "$TOTAL_RANKS"

echo -e "\n# actual run" >>$RFILE
echo "python driver.py" >> $RFILE
chmod u+x $RFILE
