#!/bin/bash
set -e

#--------------------------------------
: ${QUEUE:="prod"}
: ${NEKRS_GPU_MPI:=0}
: ${NEKRS_BACKEND:="CUDA"}
: ${RANKS_FOR_BUILD:=4}
: ${SIM_RANKS_PER_NODE:=2}
: ${TRAIN_RANKS_PER_NODE:=2}
: ${DEPLOYMENT:="colocated"}
: ${DB_NODES:=1}
: ${SIM_NODES:=1}
: ${TRAIN_NODES:=1}
: ${SIM_CPU_BIND_LIST:="24:16"}
: ${TRAIN_CPU_BIND_LIST:="8:1"}
: ${VENV_PATH:=""}
#--------------------------------------

cp tgv.par.safe tgv.par

source $NEKRS_HOME/bin/nrsqsub_utils
setup $# 1

chk_case $TOTAL_RANKS

#--------------------------------------
# Generate the workflow config script
CFILE=ssim_config.yaml
echo "# Database config" > $CFILE
echo "database:" >> $CFILE
echo "    launch: True" >> $CFILE
echo "    backend: \"redis\"" >> $CFILE
echo "    deployment: \"${DEPLOYMENT}\"" >> $CFILE
echo "    port: 6780" >> $CFILE
if [ ${DEPLOYMENT} == "colocated"  ]; then
  echo "    network_interface: \"uds\"" >> $CFILE
else
  echo "    network_interface: \"hsn0\"" >> $CFILE
fi
echo "    exp_name: \"nekRS-ML\"" >> $CFILE
echo "    launcher: \"pals\"" >> $CFILE
echo "" >> $CFILE
echo "# Run config" >> $CFILE
echo "run_args:" >> $CFILE
echo "    nodes: ${qnodes}" >> $CFILE
if [ ${DEPLOYMENT} == "colocated"  ]; then
  SIM_NODES=$nodes
  TRAIN_NODES=$nodes
  SIM_PROCS=$(( SIM_NODES * SIM_RANKS_PER_NODE ))
  TRAIN_PROCS=$(( TRAIN_NODES * TRAIN_RANKS_PER_NODE ))
  echo "    db_nodes: ${DB_NODES}" >> $CFILE
  echo "    sim_nodes: ${SIM_NODES}" >> $CFILE
  echo "    ml_nodes: ${SIM_NODES}" >> $CFILE
  echo "    simprocs: ${SIM_PROCS}" >> $CFILE
  echo "    simprocs_pn: ${SIM_RANKS_PER_NODE}" >> $CFILE
  echo "    mlprocs: ${TRAIN_PROCS}" >> $CFILE
  echo "    mlprocs_pn: ${TRAIN_RANKS_PER_NODE}" >> $CFILE
  echo "    dbprocs_pn: 4" >> $CFILE
  echo "    sim_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
  echo "    ml_cpu_bind: \"list:${TRAIN_CPU_BIND_LIST}\"" >> $CFILE
  echo "    db_cpu_bind: [28,29,30,31]" >> $CFILE
elif [ ${DEPLOYMENT} == "clustered"  ]; then
  SIM_PROCS=$(( SIM_NODES * SIM_RANKS_PER_NODE ))
  TRAIN_PROCS=$(( TRAIN_NODES * TRAIN_RANKS_PER_NODE ))
  echo "    db_nodes: ${DB_NODES}" >> $CFILE
  echo "    sim_nodes: ${SIM_NODES}" >> $CFILE
  echo "    ml_nodes: ${TRAIN_NODES}" >> $CFILE
  echo "    simprocs: ${SIM_PROCS}" >> $CFILE
  echo "    simprocs_pn: ${SIM_RANKS_PER_NODE}" >> $CFILE
  echo "    mlprocs: ${TRAIN_PROCS}" >> $CFILE
  echo "    mlprocs_pn: ${TRAIN_RANKS_PER_NODE}" >> $CFILE
  echo "    dbprocs_pn: 8" >> $CFILE
  echo "    sim_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
  echo "    ml_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
  echo "    db_cpu_bind: [1,2,3,4,5,6,7,8]" >> $CFILE
fi
echo "" >> $CFILE
echo "# Simulation config" >> $CFILE
echo "sim:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/bin/nekrs\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    arguments: \"--setup ${case}.par --backend ${NEKRS_BACKEND} \"" >> $CFILE
echo "    copy_files: [\"./${case}.usr\",\"./${case}.par\",\"./${case}.udf\",\"./${case}.re2\"]" >> $CFILE
echo "    link_files: [\".cache\"]" >> $CFILE
echo "" >> $CFILE
echo "# Trainer config" >> $CFILE
echo "train:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/3rd_party/gnn/dist-gnn/main.py\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
if [ ${DEPLOYMENT} == "colocated"  ]; then
  echo "    arguments: \"device_skip=${SIM_RANKS_PER_NODE} halo_swap_mode=all_to_all_opt layer_norm=True online=True client.db_nodes=${DB_NODES} consistency=True target_loss=2.7161e-04 verbose=True transform_x=true transform_y=true transform_z=true\"" >> $CFILE
elif [ ${DEPLOYMENT} == "clustered"  ]; then
  echo "    arguments: \"halo_swap_mode=all_to_all_opt layer_norm=True online=True client.db_nodes=${DB_NODES} consistency=True target_loss=2.7161e-04 verbose=True transform_x=true transform_y=true transform_z=true\"" >> $CFILE
fi
echo "    copy_files: []" >> $CFILE
echo "    link_files: []" >> $CFILE

#--------------------------------------
# Update the .par file with the ML options
PFILE=${case}.par
echo "" >> $PFILE
echo "[ML]" >> $PFILE
echo "ssimDeployment = ${DEPLOYMENT}" >> $PFILE
echo "ssimDbNodes = ${DB_NODES}" >> $PFILE

#--------------------------------------
# Generate the run script
RFILE=run.sh
echo "#!/bin/bash" > $RFILE

echo "export TZ='/usr/share/zoneinfo/US/Central'" >> $RFILE

echo -e "\necho Jobid: \$PBS_JOBID" >>$RFILE
echo "echo Running on host \`hostname\`" >>$RFILE
echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$RFILE

echo "module restore" >> $RFILE
echo "module use /soft/modulefiles/" >> $RFILE
echo "module load conda" >> $RFILE
echo "conda activate" >> $RFILE
echo "source ${VENV_PATH}" >> $RFILE
echo "module list" >> $RFILE

echo -e "\nexport NEKRS_HOME=$NEKRS_HOME" >>$RFILE
echo "export NEKRS_CACHE_BCAST=$NEKRS_CACHE_BCAST" >>$RFILE
echo "export NEKRS_LOCAL_TMP_DIR=/local/scratch" >>$RFILE
echo "export NEKRS_GPU_MPI=$NEKRS_GPU_MPI" >>$RFILE
echo "export MPICH_MPIIO_HINTS=$MPICH_MPIIO_HINTS" >>$RFILE
echo "export MPICH_MPIIO_STATS=0" >>$RFILE
echo "export MPICH_GPU_SUPPORT_ENABLED=0" >> $RFILE
echo "export MPICH_OFI_NIC_POLICY=NUMA" >> $RFILE

echo -e "\nexport TORCH_PATH=\$( python -c 'import torch; print(torch.__path__[0])' )" >> $RFILE
echo "export LD_LIBRARY_PATH=\$TORCH_PATH/lib:\$LD_LIBRARY_PATH" >> $RFILE
echo "export SR_SOCKET_TIMEOUT=10000" >> $RFILE

echo -e "\n# precompilation" >>$RFILE
CMD_build="mpiexec -n ${RANKS_FOR_BUILD} -ppn ${RANKS_FOR_BUILD} --cpu-bind list:24:16:8:1 -- $bin --setup ${case} --backend ${NEKRS_BACKEND}  $extra_args --build-only ${RANKS_FOR_BUILD}"
add_build_CMD "$RFILE" "$CMD_build" "$TOTAL_RANKS"

echo -e "\n# actual run" >>$RFILE
echo "python ssim_driver.py" >> $RFILE
chmod u+x $RFILE

