#!/bin/bash
set -e

#--------------------------------------
: ${QUEUE:="prod"}
: ${NEKRS_GPU_MPI:=0}
: ${NEKRS_BACKEND:="CUDA"}
: ${RANKS_FOR_BUILD:=4}
: ${SIM_RANKS_PER_NODE:=4}
: ${TRAIN_RANKS_PER_NODE:=4}
: ${DEVICE_SKIP:=0}
: ${DEPLOYMENT:="clustered"}
: ${SIM_NODES:=1}
: ${TRAIN_NODES:=1}
: ${SIM_CPU_BIND_LIST:="24:16:8:1"}
: ${TRAIN_CPU_BIND_LIST:="24:16:8:1"}
: ${INFERENCE_CPU_BIND_LIST:="24:16:8:1"}
: ${VENV_PATH:=""}
#--------------------------------------

#--------------------------------------
# Set variables based on deployment type
if [ ${DEPLOYMENT} == "colocated"  ]; then
  SIM_NODES=$nodes
  TRAIN_NODES=$nodes
  SIM_RANKS_PER_NODE=2
  TRAIN_RANKS_PER_NODE=2
  DEVICE_SKIP=2
  SIM_CPU_BIND_LIST="24:16"
  TRAIN_CPU_BIND_LIST="8:1"
fi
SIM_PROCS=$(( SIM_NODES * SIM_RANKS_PER_NODE ))
TRAIN_PROCS=$(( TRAIN_NODES * TRAIN_RANKS_PER_NODE ))


#--------------------------------------
# Copy the .par file
cp ${1}.par.safe ${1}.par

#--------------------------------------
# Update the .box file to increase the mesh size linearly with the number of nodes
NZ=$(( 20*SIM_PROCS ))
LZ=$(echo "3.141592653 * $SIM_PROCS" | bc -l)
cp ${1}.box.safe ${1}.box
sed -i "s/NZ/${NZ}/g" ${1}.box
sed -i "s/LZ/${LZ}/g" ${1}.par

#--------------------------------------
# Run genbox from Nek5000 to generate the .re2 mesh file
if [ ! -d $NEKRS_HOME/Nek5000 ]; then
  CWD=$PWD
  cd $NEKRS_HOME
  git clone https://github.com/rickybalin/Nek5000.git
  cd Nek5000/tools
  FC=ftn ./maketools genbox
  cd $CWD
fi
$NEKRS_HOME/Nek5000/bin/genbox ${1}.box ${1}

#--------------------------------------
# Setup the case
source $NEKRS_HOME/bin/nrsqsub_utils
setup $# 1
chk_case $TOTAL_RANKS

#--------------------------------------
# Generate the workflow config script
CFILE=config.yaml
echo "# Workflow config" > $CFILE
echo "scheduler: pbs" >> $CFILE
echo "deployment: \"${DEPLOYMENT}\"" >> $CFILE
echo "" >> $CFILE
echo "# Run config" >> $CFILE
echo "run_args:" >> $CFILE
echo "    nodes: ${qnodes}" >> $CFILE
echo "    sim_nodes: ${SIM_NODES}" >> $CFILE
echo "    ml_nodes: ${SIM_NODES}" >> $CFILE
echo "    simprocs: ${SIM_PROCS}" >> $CFILE
echo "    simprocs_pn: ${SIM_RANKS_PER_NODE}" >> $CFILE
echo "    mlprocs: ${TRAIN_PROCS}" >> $CFILE
echo "    mlprocs_pn: ${TRAIN_RANKS_PER_NODE}" >> $CFILE
echo "    sim_cpu_bind: \"list:${SIM_CPU_BIND_LIST}\"" >> $CFILE
echo "    ml_cpu_bind: \"list:${TRAIN_CPU_BIND_LIST}\"" >> $CFILE
echo "" >> $CFILE
echo "# Simulation config" >> $CFILE
echo "sim:" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/bin/nekrs\"" >> $CFILE
echo "    arguments: \"--setup ${case}.par --backend ${NEKRS_BACKEND} \"" >> $CFILE
echo "" >> $CFILE
echo "# Trainer config" >> $CFILE
echo "train:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/3rd_party/gnn/dist-gnn/main.py\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    arguments: \"device_skip=${DEVICE_SKIP} precision=bf16 phase1_steps=200 hidden_channels=256 n_mlp_hidden_layers=2 n_messagePassing_layers=8 halo_swap_mode=all_to_all_opt online=True client.backend=adios client.adios_transport=RDMA online_update_freq=20 time_dependency=time_dependent verbose=True transform_x=true transform_z=true\"" >> $CFILE
echo "" >> $CFILE
echo "# Inference config" >> $CFILE
echo "inference:" >> $CFILE
echo "    executable: \"${NEKRS_HOME}/3rd_party/gnn/dist-gnn/inference.py\"" >> $CFILE
echo "    affinity: \"\"" >> $CFILE
echo "    arguments: \"model_task=inference rollout_steps=200 hidden_channels=256 n_mlp_hidden_layers=2 n_messagePassing_layers=8 halo_swap_mode=all_to_all_opt online=True client.backend=adios time_dependency=time_dependent verbose=True transform_x=true transform_z=true\"" >> $CFILE

#--------------------------------------
# Update the .par file with the ML options
PFILE=${case}.par
echo "" >> $PFILE
echo "[ML]" >> $PFILE
echo "gnnPolynomialOrder = 2" >> $PFILE
echo "adiosEngine = SST" >> $PFILE
echo "adiosTransport = RDMA" >> $PFILE
echo "adiosStream = async" >> $PFILE

#--------------------------------------
# Generate the run script
RFILE=run.sh
echo "#!/bin/bash -l" > $RFILE
echo "##PBS -S /bin/bash" >> $RFILE
echo "##PBS -N nekrs-ml" >> $RFILE
echo "##PBS -l walltime=${TIME}:00" >> $RFILE
echo "##PBS -l select=$NODES" >> $RFILE
echo "##PBS -l select=home:eagle" >> $RFILE
echo "##PBS -k doe" >> $RFILE
echo "##PBS -j oe" >> $RFILE
echo "##PBS -A $PROJ_ID" >> $RFILE
echo "##PBS -q $QUEUE" >> $RFILE
echo "#cd \$PBS_O_WORKDIR" >> $RFILE

echo -e "\nexport TZ='/usr/share/zoneinfo/US/Central'" >> $RFILE

echo -e "\necho Jobid: \$PBS_JOBID" >>$RFILE
echo "echo Running on host \`hostname\`" >>$RFILE
echo "echo Running on nodes \`cat \$PBS_NODEFILE\`" >>$RFILE

echo "module use /soft/modulefiles/" >> $RFILE
echo "module load conda" >> $RFILE
echo "conda activate" >> $RFILE
echo "source ${VENV_PATH}" >> $RFILE
echo "module list" >> $RFILE

echo -e "\nexport NEKRS_HOME=$NEKRS_HOME" >>$RFILE
echo "export NEKRS_CACHE_BCAST=$NEKRS_CACHE_BCAST" >>$RFILE
echo "export NEKRS_LOCAL_TMP_DIR=/local/scratch" >>$RFILE
echo "export NEKRS_GPU_MPI=$NEKRS_GPU_MPI" >>$RFILE
echo "export MPICH_MPIIO_HINTS=$MPICH_MPIIO_HINTS" >>$RFILE
echo "export MPICH_MPIIO_STATS=0" >>$RFILE
echo "export MPICH_GPU_SUPPORT_ENABLED=0" >> $RFILE
echo "export MPICH_OFI_NIC_POLICY=NUMA" >> $RFILE

py_version=`python --version`
parsed_version=$(echo ${py_version#Python } | awk -F. '{print $1"."$2}')
echo -e "\nexport PYTHONPATH=\$PYTHONPATH:${NEKRS_HOME}/lib/python${parsed_version}/site-packages" >> $RFILE
echo "export SstVerbose=1" >> $RFILE
echo "export OMP_PROC_BIND=spread" >> $RFILE
echo "export OMP_PLACES=threads" >> $RFILE
echo "if ls *.sst 1> /dev/null 2>&1" >> $RFILE
echo "then" >> $RFILE 
echo "    echo Cleaning up old .sst files" >> $RFILE
echo "    rm *.sst" >> $RFILE
echo "fi" >> $RFILE
echo "if ls *.bp 1> /dev/null 2>&1" >> $RFILE
echo "then" >> $RFILE
echo "    echo Cleaning up old .bp files" >> $RFILE
echo "    rm -r ./*.bp" >> $RFILE
echo "fi" >> $RFILE

echo -e "\n# precompilation" >> $RFILE
echo "if [ ! -d .cache ]; then" >> $RFILE
echo "  echo Cleaning up the cache" >> $RFILE
echo "  rm -rf .cache" >> $RFILE
echo "fi" >> $RFILE
CMD_build="mpiexec -n ${RANKS_FOR_BUILD} -ppn ${RANKS_FOR_BUILD} --cpu-bind list:${SIM_CPU_BIND_LIST} -- $bin --setup ${case} --backend ${NEKRS_BACKEND}  $extra_args --build-only ${RANKS_FOR_BUILD}"
add_build_CMD "$RFILE" "$CMD_build" "$TOTAL_RANKS"

echo -e "\n# actual run" >>$RFILE
echo "python driver.py" >> $RFILE
chmod u+x $RFILE

